=== kahunapule/haiola/haiola/SFMInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xs:element name="SFMInfo">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="sfm">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tag" type="xs:string">
								<xs:annotation>
									<xs:documentation>This is the USFM tag value (without the backslash).</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="endTag" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The tag (or tags) that terminate the condition started with the associated USFM tag.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="paragraphStyle" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The named Microsoft Word paragraph style associated with this tag.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string"/>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="characterStyle" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The named Microsoft Word character style associated with this tag.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="parameterName" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The parameter name associated with the USFM marker attribute for use within program processing. The presence of a non-null value here indicates that a space-delimited parameter follows this tag, such as the verse number after \v 1.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="contentName" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The parameter name associated with the tag contents for use within program processing.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="nestingAllowed" type="xs:boolean" minOccurs="0">
								<xs:annotation>
									<xs:documentation>true iff other markers are allowed to nest within this marker's contents.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="levelExpected" type="xs:boolean" minOccurs="0">
								<xs:annotation>
									<xs:documentation>true iff the USFM tag incorporates a number indicating level as the last part of the tag, such as \q1 or \q2 for different indent levels of poetry. This parameter is converted to a "level" attribute in USFX.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="usfx" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The USFX element name corresponding to the USFM tag.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="usfxAttribute" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The name of the attribute associated with the parameter after this tag when a parameterName is specified. For example, this would be "id" for chapter or verse.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="milestone" type="xs:boolean" minOccurs="0">
								<xs:annotation>
									<xs:documentation>True iff this SFM is to be converted to a milestone instead of a container. In the case of chapter and verse markers, they are marked as milestones here, but may contain a redundant chapter or verse marking, repeating the marking of the attribute. This redundant marking is lost on conversion back to USFM.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="TeXcode" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>This is the TeX code (without the backslash) that this tag is translated to when converting to TeX.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="defaultAttribute">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="sequence" type="xs:int"/>
											<xs:attribute name="usfxName" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="comment" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Free-form text indicating the purpose of this tag.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="kind" type="xs:string" default="paragraph"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kahunapule/haiola/phrasetrans/SFMInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- created by Kahunapule Michael Johnson, and released under LGPL 3 or later -->
<SFMInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SFMInfo.xsd">
	<sfm kind="ignore">
		<tag>-tag-</tag>
		<endTag>tag*</endTag>
		<paragraphStyle>paragraph style</paragraphStyle>
		<characterStyle>character style</characterStyle>
		<parameterName>parameter name</parameterName>
		<contentName>content name</contentName>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<usfx>USFX</usfx>
		<usfxAttribute>USFX attribute</usfxAttribute>
		<milestone>false</milestone>
		<TeXcode>TeX</TeXcode>
		<comment>comment</comment>
	</sfm>
	<sfm kind="character">
		<tag>add</tag>
		<endTag>add*</endTag>
		<characterStyle>Supplied</characterStyle>
		<nestingAllowed>true</nestingAllowed>
		<levelExpected>false</levelExpected>
		<usfx>add</usfx>
		<milestone>false</milestone>
		<comment>Added words (i. e. KJV italics)</comment>
	</sfm>
	<sfm kind="paragraph">
		<tag>b</tag>
		<paragraphStyle>Stanza Break</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<milestone>false</milestone>
		<TeXcode>blankLine</TeXcode>
		<comment>Blank line between poetry stanzas; no text should follow this marker</comment>
	</sfm>
	<sfm kind="character">
		<tag>bd</tag>
		<endTag>bd*</endTag>
		<characterStyle>Bold</characterStyle>
		<nestingAllowed>true</nestingAllowed>
		<levelExpected>false</levelExpected>
		<milestone>false</milestone>
		<comment>Not recommended</comment>
	</sfm>
	<sfm kind="character">
		<tag>bdit</tag>
		<endTag>bdit*</endTag>
		<characterStyle>Bold italic</characterStyle>
		<nestingAllowed>true</nestingAllowed>
		<levelExpected>false</levelExpected>
		<milestone>false</milestone>
		<comment>Not recommended</comment>
	</sfm>
	<sfm kind="character">
		<tag>bk</tag>
		<endTag>bk*</endTag>
		<characterStyle>Book Title In Text</characterStyle>
		<nestingAllowed>true</nestingAllowed>
		<levelExpected>false</levelExpected>
		<milestone>false</milestone>
	</sfm>
	<sfm kind="meta">
		<tag>c</tag>
		<parameterName>currentChapter</parameterName>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<milestone>true</milestone>
	</sfm>
	<sfm kind="meta">
		<tag>ca</tag>
		<endTag>ca*</endTag><parameterName>altChapter</parameterName>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<milestone>true</milestone>
	</sfm>
	<sfm kind="paragraph">
		<tag>cd</tag>
		<paragraphStyle>Chapter description</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<TeXcode>chapDesc</TeXcode>
	</sfm>
	<sfm kind="meta">
		<tag>cl</tag>
		<contentName>chapterLabel</contentName>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="paragraph">
		<tag>cls</tag>
		<paragraphStyle>Greeting</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<comment>Complementary closing of a letter</comment>
	</sfm>
	<sfm kind="paragraph">
		<tag>conc</tag>
		<paragraphStyle>Concordance</paragraphStyle>
		<levelExpected>false</levelExpected>
		<usfx>concordance</usfx>
		<milestone>false</milestone>
		<comment>Begin concordance</comment>
	</sfm>
	<sfm kind="paragraph">
		<tag>cov</tag>
		<paragraphStyle>Cover</paragraphStyle>
		<levelExpected>false</levelExpected>
		<usfx>cover</usfx>
		<milestone>false</milestone>
		<comment>Begin cover</comment>
	</sfm>
	<sfm kind="meta">
		<tag>cp</tag>
		<parameterName>pubChapter</parameterName>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="paragraph">
		<tag>d</tag>
		<paragraphStyle>Hebrew Title</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<TeXcode>hebTitle</TeXcode>
	</sfm>
	<sfm kind="dc">
		<tag>dc</tag>
		<endTag>dc*</endTag>
		<characterStyle>Deuterocanon</characterStyle>
		<nestingAllowed>true</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="meta">
		<tag>e</tag>
		<paragraphStyle>Invisible Paragraph</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<comment>Ignored</comment>
	</sfm>
	<sfm kind="paragraph">
		<tag>ebm</tag>
		<paragraphStyle>Bridge left</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="paragraph">
		<tag>ebp</tag>
		<paragraphStyle>Bridge paragraph</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="paragraph">
		<tag>ebq</tag>
		<paragraphStyle>Bridge poetry</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>true</levelExpected>
	</sfm>
	<sfm kind="paragraph">
		<tag>ebs</tag>
		<paragraphStyle>Bridge title</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>true</levelExpected>
	</sfm>
	<sfm kind="character">
		<tag>em</tag>
		<endTag>em*</endTag>
		<characterStyle>Emphasized</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<comment>Emphasis, maybe bold</comment>
	</sfm>
	<sfm kind="note">
		<tag>f</tag>
		<endTag>f*</endTag>
		<characterStyle>Footnote</characterStyle>
		<parameterName>footnoteCaller</parameterName>
		<nestingAllowed>true</nestingAllowed>
		<levelExpected>false</levelExpected>
		<usfx>f</usfx>
		<usfxAttribute>caller</usfxAttribute>
	</sfm>
	<sfm kind="dc">
		<tag>fdc</tag>
		<endTag>fdc*</endTag>
		<characterStyle>Footnote Deuterocanon</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<comment>Invisible unless Deuterocanon included</comment>
	</sfm>
	<sfm kind="note">
		<tag>fe</tag>
		<endTag>fe*</endTag>
		<characterStyle>Endnote</characterStyle>
		<parameterName>endnoteCaller</parameterName>
		<nestingAllowed>true</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="figure">
		<tag>fig</tag>
		<endTag>fig*</endTag>
		<characterStyle>Figure</characterStyle>
		<nestingAllowed>true</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="character">
		<tag>fk</tag>
		<endTag>fk*</endTag>
		<characterStyle>Referenced Text</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="note">
		<tag>fl</tag>
		<endTag>fl*,ft,fk,fq,fv,fqa, f*</endTag>
		<characterStyle>Footnote Label</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<comment>For marking or labelling words which are consistently used across certain kinds of translation notes, like "or". Not very useful.</comment>
	</sfm>
	<sfm kind="character">
		<tag>fm</tag>
		<endTag>fm*</endTag>
		<characterStyle>Footnote marker</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<comment>Simple superscript; not recommended</comment>
	</sfm>
	<sfm kind="paragraph">
		<tag>fp</tag>
		<paragraphStyle>Footnote normal</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<comment>For a paragraph break within a footnote (for very long-winded footnotes).</comment>
	</sfm>
	<sfm kind="character">
		<tag>fq</tag>
		<endTag>fq*,ft,fk,fq,fv,fqa, f*</endTag>
		<characterStyle>Quoted from text</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="character">
		<tag>fqa</tag>
		<endTag>fqa*,fq,ft,fk,fv, f*</endTag>
		<characterStyle>Alternate Reading</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="character">
		<tag>fr</tag>
		<endTag>fr*, f*</endTag>
		<characterStyle>Note Target Reference</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="character">
		<tag>ft</tag>
		<endTag>ft*,fk,fq,fv</endTag>
		<characterStyle>Footnote</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="character">
		<tag>fv</tag>
		<endTag>fv*,fq,ft,fk,fv</endTag>
		<characterStyle>Verse Number In Note</characterStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
	</sfm>
	<sfm kind="paragraph">
		<tag>glo</tag>
		<paragraphStyle>Glossary</paragraphStyle>
		<levelExpected>false</levelExpected>
		<usfx>glossary</usfx>
		<milestone>false</milestone>
		<comment>Begin glossary</comment>
	</sfm>
	<sfm kind="meta">
		<tag>h</tag>
		<paragraphStyle>Invisible Paragraph</paragraphStyle>
		<contentName>shortName</contentName>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>true</levelExpected>
		<usfx>h</usfx>
		<milestone>false</milestone>
		<comment>Short name for a book of the Bible, like "Mark".</comment>
	</sfm>
	<sfm kind="paragraph">
		<tag>hr</tag>
		<paragraphStyle>Horizontal Rule</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<comment>Not USFM; retained from PNGSFM: horizontal rule</comment>
	</sfm>
	<sfm kind="paragraph">
		<tag>ib</tag>
		<paragraphStyle>Intro Stanza Break</paragraphStyle>
		<nestingAllowed>false</nestingAllowed>
		<levelExpected>false</levelExpected>
		<TeXcode>introBlankLine</TeXcode>
	</sfm>
	<sfm kind="meta">
		<tag>id</tag>
		<paragraphStyle>Invisible Paragraph</paragraphStyle>
		<parameterName>bookName</parameterName>
		<contentName>id</contentName>
