=== kahunapule/haiola/sepp/crossreferences.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="crossreferences">
		<xs:annotation>
			<xs:documentation>Scripture verse crossreferences</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="xlat" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="source" type="xs:string"/>
							<xs:element name="target" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="xref" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="at" type="xs:string"/>
							<xs:element name="note" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kahunapule/haiola/haiola/crossreference.xml
<?xml version="1.0" encoding="UTF-8"?>
<crossreferences xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\sil\Onyx\crossreferences.xsd">
	<comment>This is a set of crossreferences from the World English Bible New Testament.</comment>
	<xlat>
		<source>Genesis</source>
		<target>GEN</target>
	</xlat>
	<xlat>
		<source>Exodus</source>
		<target>EXO</target>
	</xlat>
	<xlat>
		<source>Leviticus</source>
		<target>LEV</target>
	</xlat>
	<xlat>
		<source>Numbers</source>
		<target>NUM</target>
	</xlat>
	<xlat>
		<source>Deuteronomy</source>
		<target>DEU</target>
	</xlat>
	<xlat>
		<source>Joshua</source>
		<target>JOS</target>
	</xlat>
	<xlat>
		<source>Judges</source>
		<target>JDG</target>
	</xlat>
	<xlat>
		<source>Ruth</source>
		<target>RUT</target>
	</xlat>
	<xlat>
		<source>1 Samuel</source>
		<target>1SA</target>
	</xlat>
	<xlat>
		<source>2 Samuel</source>
		<target>2SA</target>
	</xlat>
	<xlat>
		<source>1 Kings</source>
		<target>1KI</target>
	</xlat>
	<xlat>
		<source>2 Kings</source>
		<target>2KI</target>
	</xlat>
	<xlat>
		<source>1 Chronicles</source>
		<target>1CH</target>
	</xlat>
	<xlat>
		<source>2 Chronicles</source>
		<target>2CH</target>
	</xlat>
	<xlat>
		<source>Ezra</source>
		<target>EZR</target>
	</xlat>
	<xlat>
		<source>Nehemiah</source>
		<target>NEH</target>
	</xlat>
	<xlat>
		<source>Esther</source>
		<target>EST</target>
	</xlat>
	<xlat>
		<source>Job</source>
		<target>JOB</target>
	</xlat>
	<xlat>
		<source>Psalm</source>
		<target>PSA</target>
	</xlat>
	<xlat>
		<source>Proverbs</source>
		<target>PRO</target>
	</xlat>
	<xlat>
		<source>Ecclesiastes</source>
		<target>ECC</target>
	</xlat>
	<xlat>
		<source>Song of Songs</source>
		<target>SNG</target>
	</xlat>
	<xlat>
		<source>Isaiah</source>
		<target>ISA</target>
	</xlat>
	<xlat>
		<source>Jeremiah</source>
		<target>JER</target>
	</xlat>
	<xlat>
		<source>Lamentations</source>
		<target>LAM</target>
	</xlat>
	<xlat>
		<source>Ezekiel</source>
		<target>EZK</target>
	</xlat>
	<xlat>
		<source>Daniel</source>
		<target>DAN</target>
	</xlat>
	<xlat>
		<source>Hosea</source>
		<target>HOS</target>
	</xlat>
	<xlat>
		<source>Joel</source>
		<target>JOL</target>
	</xlat>
	<xlat>
		<source>Amos</source>
		<target>AMO</target>
	</xlat>
	<xlat>
		<source>Obadiah</source>
		<target>OBA</target>
	</xlat>
	<xlat>
		<source>Jonah</source>
		<target>JON</target>
	</xlat>
	<xlat>
		<source>Micah</source>
		<target>MIC</target>
	</xlat>
	<xlat>
		<source>Nahum</source>
		<target>NAH</target>
	</xlat>
	<xlat>
		<source>Habakuk</source>
		<target>HAB</target>
	</xlat>
	<xlat>
		<source>Zephaniah</source>
		<target>ZEP</target>
	</xlat>
	<xlat>
		<source>Haggai</source>
		<target>HAG</target>
	</xlat>
	<xlat>
		<source>Zechariah</source>
		<target>ZEC</target>
	</xlat>
	<xlat>
		<source>Malachi</source>
		<target>MAL</target>
	</xlat>
	<xlat>
		<source>Matthew</source>
		<target>MAT</target>
	</xlat>
	<xlat>
		<source>Mark</source>
		<target>MRK</target>
	</xlat>
	<xlat>
		<source>Luke</source>
		<target>LUK</target>
	</xlat>
	<xlat>
		<source>John</source>
		<target>JHN</target>
	</xlat>
	<xlat>
		<source>Acts</source>
		<target>ACT</target>
	</xlat>
	<xlat>
		<source>Romans</source>
		<target>ROM</target>
	</xlat>
	<xlat>
		<source>1 Corinthians</source>
		<target>1CO</target>
	</xlat>
	<xlat>
		<source>2 Corinthians</source>
		<target>2CO</target>
	</xlat>
	<xlat>
		<source>Galatians</source>
		<target>GAL</target>
	</xlat>
	<xlat>
		<source>Ephesians</source>
		<target>EPH</target>
	</xlat>
	<xlat>
		<source>Philippians</source>
		<target>PHP</target>
	</xlat>
	<xlat>
		<source>Colossians</source>
		<target>COL</target>
	</xlat>
	<xlat>
		<source>1 Thessalonians</source>
		<target>1TH</target>
	</xlat>
	<xlat>
		<source>2 Thessalonians</source>
		<target>2TH</target>
	</xlat>
	<xlat>
		<source>1 Timothy</source>
		<target>1TI</target>
	</xlat>
	<xlat>
		<source>2 Timothy</source>
		<target>2TI</target>
	</xlat>
	<xlat>
		<source>Titus</source>
		<target>TIT</target>
	</xlat>
	<xlat>
		<source>Philemon</source>
		<target>PHM</target>
	</xlat>
	<xlat>
		<source>Hebrews</source>
		<target>HEB</target>
	</xlat>
	<xlat>
		<source>James</source>
		<target>JAS</target>
	</xlat>
	<xlat>
		<source>1 Peter</source>
		<target>1PE</target>
	</xlat>
	<xlat>
		<source>2 Peter</source>
		<target>2PE</target>
	</xlat>
	<xlat>
		<source>1 John</source>
		<target>1JN</target>
	</xlat>
	<xlat>
		<source>2 John</source>
		<target>2JN</target>
	</xlat>
	<xlat>
		<source>3 John</source>
		<target>3JN</target>
	</xlat>
	<xlat>
		<source>Jude</source>
		<target>JUD</target>
	</xlat>
	<xlat>
		<source>Revelation</source>
		<target>REV</target>
	</xlat>
	<xref>
		<at>MAT 1:23</at>
		<note>Isaiah 7:14</note>
	</xref>
	<xref>
		<at>MAT 2:6</at>
		<note>Micah 5:2</note>
	</xref>
	<xref>
		<at>MAT 2:15</at>
		<note>Hosea 11:1</note>
	</xref>
	<xref>
		<at>MAT 2:18</at>
		<note>Jeremiah 31:15</note>
	</xref>
	<xref>
		<at>MAT 3:3</at>
		<note>Isaiah 40:3</note>
	</xref>
	<xref>
		<at>MAT 4:4</at>
		<note>Deuteronomy 8:3</note>
	</xref>
	<xref>
		<at>MAT 4:6</at>
		<note>Psalm 91:11-12</note>
	</xref>
	<xref>
		<at>MAT 4:7</at>
		<note>Deuteronomy 6:16</note>
	</xref>
	<xref>
		<at>MAT 4:10</at>
		<note>Deuteronomy 6:13</note>
	</xref>
	<xref>
		<at>MAT 4:16</at>
		<note>Isaiah 9:1-2</note>
	</xref>
	<xref>
		<at>MAT 5:3</at>
		<note>Isaiah 57:15; 66:2</note>
	</xref>
	<xref>
		<at>MAT 5:4</at>
		<note>Isaiah 61:2; 66:10,13</note>
	</xref>
	<xref>
		<at>MAT 5:5</at>
		<note>Psalm 37:11</note>
	</xref>
	<xref>
		<at>MAT 5:21</at>
		<note>Exodus 20:13</note>
	</xref>
	<xref>
		<at>MAT 5:27</at>
		<note>Exodus 20:14</note>
	</xref>
	<xref>
		<at>MAT 5:31</at>
		<note>Deuteronomy 24:1</note>
	</xref>
	<xref>
		<at>MAT 5:38</at>
		<note>Exodus 21:24; Leviticus 24:20; Deuteronomy 19:21</note>
	</xref>
	<xref>
		<at>MAT 5:43</at>
		<note>Leviticus 19:18</note>
	</xref>
	<xref>
		<at>MAT 8:17</at>
		<note>Isaiah 53:4</note>
	</xref>
	<xref>
		<at>MAT 9:13</at>
		<note>Hosea 6:6</note>
	</xref>
	<xref>
		<at>MAT 10:36</at>
		<note>Micah 7:6</note>
	</xref>
	<xref>
		<at>MAT 11:5</at>
		<note>Isaiah 35:5</note>
	</xref>
	<xref>
		<at>MAT 11:5</at>
		<note>Isaiah 61:1-4</note>
	</xref>
	<xref>
		<at>MAT 11:10</at>
		<note>Malachi 3:1</note>
	</xref>
	<xref>
		<at>MAT 12:4</at>
		<note>1 Samuel 21:3-6</note>
	</xref>
	<xref>
		<at>MAT 12:7</at>
		<note>Hosea 6:6</note>
	</xref>
	<xref>
		<at>MAT 12:21</at>
		<note>Isaiah 42:1-4</note>
	</xref>
	<xref>
		<at>MAT 13:15</at>
		<note>Isaiah 6:9-10</note>
	</xref>
	<xref>
		<at>MAT 13:35</at>
		<note>Psalm 78:2</note>
	</xref>
	<xref>
		<at>MAT 14:25</at>
		<note>Job 9:8</note>
	</xref>
	<xref>
		<at>MAT 15:4</at>
		<note>Exodus 20:12; Deuteronomy 5:16</note>
	</xref>
	<xref>
		<at>MAT 15:4</at>
		<note>Exodus 21:17; Leviticus 20:9</note>
	</xref>
	<xref>
		<at>MAT 15:9</at>
		<note>Isaiah 29:13</note>
	</xref>
	<xref>
		<at>MAT 18:16</at>
		<note>Deuteronomy 19:15</note>
	</xref>
	<xref>
		<at>MAT 19:4</at>
		<note>Genesis 1:27</note>
	</xref>
	<xref>
		<at>MAT 19:5</at>
		<note>Genesis 2:24</note>
	</xref>
	<xref>
		<at>MAT 19:19</at>
		<note>Exodus 20:12-16; Deuteronomy 5:16-20</note>
	</xref>
	<xref>
		<at>MAT 19:19</at>
		<note>Leviticus 19:18</note>
	</xref>
	<xref>
		<at>MAT 21:5</at>
		<note>Zechariah 9:9</note>
	</xref>
	<xref>
		<at>MAT 21:9</at>
		<note>Psalm 118:26</note>
	</xref>
	<xref>
		<at>MAT 21:13</at>
		<note>Isaiah 56:7</note>
	</xref>
	<xref>
		<at>MAT 21:13</at>
		<note>Jeremiah 7:11</note>
	</xref>
	<xref>
		<at>MAT 21:16</at>
		<note>Psalm 8:2</note>
	</xref>
	<xref>
		<at>MAT 21:42</at>
		<note>Psalm 118:22-23</note>
	</xref>
	<xref>
		<at>MAT 22:32</at>
		<note>Exodus 3:6</note>
	</xref>
	<xref>
		<at>MAT 22:37</at>
		<note>Deuteronomy 6:5</note>
	</xref>
	<xref>
		<at>MAT 22:39</at>
		<note>Leviticus 19:18</note>
	</xref>
	<xref>
		<at>MAT 22:44</at>
		<note>Psalm 110:1</note>
	</xref>
	<xref>
		<at>MAT 23:39</at>
		<note>Psalm 118:26</note>
	</xref>
	<xref>
		<at>MAT 24:15</at>
		<note>Daniel 9:27; 11:31; 12:11</note>
	</xref>
	<xref>
		<at>MAT 24:29</at>
		<note>Isaiah 13:10; 34:4</note>
	</xref>
	<xref>
		<at>MAT 26:31</at>
		<note>Zechariah 13:7</note>
	</xref>
	<xref>
		<at>MAT 27:10</at>
		<note>Zechariah 11:12-13; Jeremiah 19:1-13; 32:6-9</note>
	</xref>
	<xref>
		<at>MAT 27:46</at>
		<note>Psalm 22:1</note>
	</xref>
	<xref>
		<at>MRK 1:2</at>
		<note>Malachi 3:1</note>
	</xref>
	<xref>
		<at>MRK 1:3</at>
		<note>Isaiah 40:3</note>
	</xref>
	<xref>
		<at>MRK 4:12</at>
		<note>Isaiah 6:9-10</note>
	</xref>
	<xref>
		<at>MRK 6:48</at>
		<note>Job 9:8</note>
	</xref>
	<xref>
		<at>MRK 7:7</at>
		<note>Isaiah 29:13</note>
	</xref>
	<xref>
		<at>MRK 7:10</at>
		<note>Exodus 20:12; Deuteronomy 5:16</note>
	</xref>
	<xref>
		<at>MRK 7:10</at>
		<note>Exodus 21:17; Leviticus 20:9</note>
	</xref>
	<xref>
		<at>MRK 9:48</at>
		<note>Isaiah 66:24</note>
	</xref>
	<xref>
		<at>MRK 10:6</at>
		<note>Genesis 1:27</note>
	</xref>
	<xref>
		<at>MRK 10:8</at>
		<note>Genesis 2:24</note>
	</xref>
	<xref>
		<at>MRK 10:19</at>
		<note>Exodus 20:12-16; Deuteronomy 5:16-20</note>
	</xref>
	<xref>
		<at>MRK 11:9</at>
		<note>Psalm 118:25-26</note>
	</xref>
	<xref>
		<at>MRK 11:17</at>
		<note>Isaiah 56:7</note>
	</xref>
	<xref>
		<at>MRK 11:17</at>
		<note>Jeremiah 7:11</note>
	</xref>
	<xref>
		<at>MRK 12:11</at>
		<note>Psalm 118:22-23</note>
